# Generated by Django 5.2.12 on 2026-10-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0003_photo_height_photo_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="taken_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
