# Generated by Django 5.2.12 on 2026-03-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='confidence',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
