# Generated by Django 5.2.12 on 2026-03-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0002_face_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
    ]
