# Generated by Django 5.2.12 on 2026-03-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0003_face_face_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
