# Generated by Django 5.2.12 on 2026-03-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0004_face_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
